headers:
  - ZONA
  - CANAL
  - FECHA SUBID
  - FECHA VENTA
  - CONTRATA GAS
  - CONTRATA LUZ
  - CONTRATA FUNCIONA
  - CONTRATA FACTURACIÓN ELECTRÓNICA
  - MARCA CALDERA
  - PLAN CONTRATADO
  - TIPO ALTA GAS
  - NOMBRE GAS
  - APELLIDOS GAS
  - NIF GAS
  - CUPS GAS
  - TARIFA GAS
  - DIRECCIÓN GAS
  - CP GAS
  - CONTADOR GAS
  - TIPO ALTA LUZ
  - NOMBRE LUZ
  - APELLIDOS LUZ
  - NIF LUZ
  - CUPS LUZ
  - TARIFA LUZ
  - POTENCIA DESEADA LUZ
  - CÓDIGO CIE*
  - CÓDIGO INSTALADOR CIE*
  - NOMBRE/RAZÓNDEL INSTALADOR*
  - POTENCIA DE LA INSTALACIÓN*
  - FECHA INICIO VALIDEZ CIE*
  - FECHA CADUCIDAD CIE*
  - TENSIÓN SUMINISTRO*
  - DIRECCIÓN LUZ
  - CP LUZ
  - CONTADOR LUZ
  - MUNICIPIO
  - PROVINCIA
  - TELÓFONO 1
  - TELÓFONO 2
  - TITULAR FINAL
  - Nº DE CUENTA
  - CORREO ELECTRÓNICO
  - LOPD
  - CIG (CÓDIGO GRABACIÓN)
  - OBSERVACIONES
  - FACTURAR
  - ESTADO BO
  - MOTIVO
  - FECHA ULT. GESTIÓN BO
  - USUARIO BO
  - OPORTUNIDAD
  - COMENTARIOS BO
  - RESPUESTA CANAL
  - COMENTARIOS BO 2
  - RESPUESTA CANAL 2
  - COMENTARIOS BO 3
  - RESPUESTA CANAL 3
  - Comercial